### ISSUE TITLE
Plugin simply crashes on search

### ISSUE THREAD

**Issue by Etherpanda** [fmauNeko/MarketBoardPlugin#14]
No matter how many times i reinstall or hard delete, the plugin will launch with the /pmb command then when i click on something to pull a request it just crashes and provides me with a contact the developer and restart my game prompt, then the plugin dies until I either restart or reinstall.
![pmb error](https://user-images.githubusercontent.com/84007425/117776959-05c87980-b234-11eb-8c12-5fc4c67db1c1.png)

**Comment by fmauNeko** [comment]
Hello,

As this is an old issue, I'm going to close it.

If you are still having problems, feel free to reopen an issue and/or ask for help on the XIVLauncher Discord.

Have a good day !
