### ISSUE TITLE
[FEATURE REQUEST] Shopping List (for Cross-World)

### ISSUE THREAD

**Issue by someONEgood** [fmauNeko/MarketBoardPlugin#20]
**Firstly, thank you for this wonderful wonderful plugin. Your work to create this is very much appreciated.**

As for the feature request, I was wondering if it would be possible to add a shopping list of sorts?
For instance say you just hit 80 and wanted to buy a full set of Exarchic gear; it would be nice if we could right-click items from the Market Data list, then "Add to Shopping List". This would then create a separate window that simply lists [Item Name, Price, and World] for easy reference when world hopping. Please consider it.

**Even if this isn't a possibility or you've no interest in implementing it, thank you again for this great utility.**

**Comment by fmauNeko** [comment]
Closed by #37.
