### ISSUE TITLE
Context menu integration

### ISSUE THREAD

**Issue by hsramm** [fmauNeko/MarketBoardPlugin#30]
This setting seems to not be working as it's checked and right-clicking items does not bring up the contextual menu item "Search using Market Board" or whatever the option said pre-6.1.

However, in the other setting, hovering over items still works.

**Comment by fmauNeko** [comment]
Context menus are broken in Dalamud right now, had to temporarily disable them.
They will come back ASAP.

I'll close that issue when they are back.

**Comment by hsramm** [comment]
> Context menus are broken in Dalamud right now, had to temporarily disable them. They will come back ASAP.
> 
> I'll close that issue when they are back.

Good to know. Thank you!

**Comment by Valgrifer** [comment]
Context menus, work now on fflogviewer

**Comment by fmauNeko** [comment]
In that plugin, they have been added reusing an old unmaintained version of XivCommon, which I will not do.
I will wait on goatcorp/Dalamud#821 instead.

**Comment by traugdor** [comment]
It looks like they fixed it 4 days ago. https://github.com/goatcorp/Dalamud/pull/821

**Comment by fmauNeko** [comment]
It's not merged yet, I'm tracking the PR and will do what's required when everything's good

**Comment by kalilistic** [comment]
The dalamud PR died but I ended up copying Anna's work into a separate library. Opened a PR. https://github.com/fmauNeko/MarketBoardPlugin/pull/33.
