### ISSUE TITLE
Watch for hovered item only works for items you have pulled up the listings for

### ISSUE THREAD

**Issue by Viverea** [fmauNeko/MarketBoardPlugin#31]
As title states.
For e.g. you pull up the listings for Giant Pumpkin on the plugin. Only Giant Pumpkins can be hovered over to refresh the listings. Once you pull up the listings for Palm Sugar instead, hovering over Giant Pumpkins no longer work. Instead, only Palm Sugars can be hovered over to refresh the listings.
I have no idea what's the behavior if no listings are pulled up yet (I will update whenever I restart my game).

**Comment by Pythyu** [comment]
Are you still having the issue ? The hovering should work correctly as it is now. If you're not having it anymore you might want to close the issue :D

**Comment by Viverea** [comment]
Yes, it is working to a certain extent now. However, I would like to point out that this is currently only working for items that are filtered (e.g. if you have Spectral in the search bar, anything without Spectral in its name will not trigger the hover). This might be the original problematic behavior I had inaccurately described in this issue.

**Comment by Pythyu** [comment]
Yea confirmed the issue =), I'll look to fix that.

**Comment by Pythyu** [comment]
Fix implemented in #41
