### ISSUE TITLE
can we get a "cross-datacenter" option?

### ISSUE THREAD

**Issue by LastExceed** [fmauNeko/MarketBoardPlugin#36]
similar to the cross-world option which we already have. should of course be limited to the data centers within a given region

**Comment by fmauNeko** [comment]
It's already implemented in the latest version, you have a "Cross DC" option above the "Cross World" choice !
![image](https://user-images.githubusercontent.com/46060/180047412-7e94e55a-c403-4713-ad0a-54f456a00c17.png)

**Comment by LastExceed** [comment]
oh, i must have used an outdated version then (will check tomorrow), good stuff!
