### ISSUE TITLE
[Feature Request] Separate settings window

### ISSUE THREAD

**Issue by fmauNeko** [fmauNeko/MarketBoardPlugin#38]
Move the settings in a separate window

**Comment by Pythyu** [comment]
I'll work on it today, any idea about how the window should appear ? For example, a button where ? Right click pop up ?

**Comment by Pythyu** [comment]
I put the button there, not sure if there's a better place
![Settingwin](https://user-images.githubusercontent.com/45374460/180976520-98e6974e-2531-44c5-a147-325c2373d36e.png)

**Comment by Pythyu** [comment]
Feature implemented in #40
