### ISSUE TITLE
random huge fps drop while opening the MB plugin UI

### ISSUE THREAD

**Issue by Kaiay** [fmauNeko/MarketBoardPlugin#46]
I use the file provided to solve the hovered item not working, but I don't know what's the reason to cause fps drop (around 40 fps drop, I'm playing in 60fps).
I checked if I click the right up conner arrow to make the UI become taskbar only , the problem solve immediately.
Am I the only ppl have this problem? Then I may think that's my PC problem.

**Comment by Pythyu** [comment]
Uhmm what we can do to guess if it's your PC or a problem with the fix is to check first if you have the same issue with the last standart release of the plugin in dalamud.
If you have it on both version it may come from your PC otherwise it may not.
And I guess you have the drop just by opening it up the UI without doing any specific action ?
And is the drop as long as the window is open or is it a fps drop when you open it but a few sec after it goes back to 60 fps ?

**Comment by Pythyu** [comment]
Just tested the linked build on my side, no drop in fps there

**Comment by Kaiay** [comment]
Thanks for the test. I just clean reinstalled the plugin with XIVLauncher and try to find what causing the problem.
After clean reinstalled(v0.7.0.0), hovered item still work. But the fps drop problem still. This time I notice that the problem only happen in some condition. Checking some Materia's pricing will cause fps drop. I don't know why lol.
I give some example:
I'm playing in JP DC with JP UI
checking 天眼のアルテマテリジャ(Heavens' Eye Materia X) will cause fps drop
checking アラグ白金貨(Allagan Platinum Piece) will NOT cause fps drop
checking ヘアカタログ:サイドテール(Modern Aesthetics - Both Ways) will NOT cause fps drop
checking パンプキンポタージュ(Pumpkin Potage) will cause fps drop
checking 眼力の幻薬G6(Grade 6 Tincture of Dexterity) will NOT cause fps drop
checking パンプキンラタトゥイユ(Pumpkin Ratatouille) will cause small fps drop(this one only drops 5-10 fps the others drop ~20 fps)
checking 雄略のオメガマテリジャ(Savage Might Materia IX) will cause fps drop

The fps drop only happen when the price data is finish loaded, fps remain 60 before price data is loaded.
I'm confused LAMO.

**Comment by Pythyu** [comment]
uhmm if you do /xldev and you go to Dalamud>Open Log Window in the setting Icon try in Verbose and Information to see if some interesting logs shows up when you check some pricing you know will cause an fps drops. Another try could be to see if you change language in english and re do the same test to check if language affect your fps drops maybe ?

**Comment by Kaiay** [comment]
The log have no diffence , it shows 2 VRB lines about HoverItemId whatever it is fps drops item or not.
Also checked in English UI and problem is still here.🤣
Maybe my PC can't handle Materia prices because it is too expensive now? lol

**Comment by Pythyu** [comment]
You can try to checkout the Profiler in Dalamud>Open Profiler to get more insight, I could help with that if you want. Hit me up on discord : Marethyu#4284
