### ISSUE TITLE
[Request] Option to remove the gil symbol beside prices

### ISSUE THREAD

**Issue by Rueby** [fmauNeko/MarketBoardPlugin#48]
**_Copied from Plugin-suggestions_**

"Add an option to remove the gil icon. I keep thinking there's one more digit than there is because of it. IMO it adds no clarity or help, people know what currency the game uses, and it's not as if there's ever a situation where something other than gil is used."

**Comment by Pythyu** [comment]
Thanks for the feedback :)
I'll make an option for it, should be easy.
I should check out the plugin-suggestion channel from time to time xD

**Comment by Rueby** [comment]
Awesome thanks alot!

**Comment by Pythyu** [comment]
Solved in #49

if you feel like trying it out and/or give me some feedback, here is the build : [https://github.com/Pythyu/MarketBoardPlugin/releases](https://github.com/Pythyu/MarketBoardPlugin/releases)
