### ISSUE TITLE
Enhancement: Option to disable "Right Click" Menu Entry

### ISSUE THREAD

**Issue by ScarVite** [fmauNeko/MarketBoardPlugin#53]
Hey, it would be lovely if you could add an option for us to disable the menu entry for "Search with Market Bord plugin".
I Personally like to have my HUD without any modded interface and that just kinda disturbs that.

![ffxiv_dx11_HhIYeXva3J](https://user-images.githubusercontent.com/43887376/187365052-bdc2749d-40b8-4fe8-b62b-313bc2019215.png)

**Comment by fmauNeko** [comment]
There's a "Context menu integration" checkbox in the settings.
