### ISSUE TITLE
[Feature Request] Filter results by quantity

### ISSUE THREAD

**Issue by nothingfromzero** [fmauNeko/MarketBoardPlugin#55]
The ability to filter results greater or less than a certain quantity would be very helpful in removing clutter in results from very low units posted multiple times. It also would help to find what worlds/datacenters are worth the trip because they have enough concentration of the item you want rather than making multiple trips.

Thanks for your consideration.

**Comment by Pythyu** [comment]
Good idea, should not be too hard to implement.
I'll do some tries and I get back to you to check if I didn't miss anything ^^

**Comment by Pythyu** [comment]
Here's an update @nothingfromzero o/
So for now it looks like that 
![minqte](https://user-images.githubusercontent.com/45374460/188238786-8fd98718-913a-4a70-8907-8f419c6138de.png)
I made the filter to only apply on current listing and not on the market history, what do you think ? Is it better to not apply the filter on the market history or to apply it to the market history as well ?

**Comment by nothingfromzero** [comment]
Great work! Very excited to see this implemented and use it in the future. I hadn't thought about applying it to market history, but if you were, I think it would be best if we were able to apply it separately. Or not at all. It's useful to compare smaller and larger quantities so we can see if people tend to buy smaller or larger stacks while having current listings at a different min quantity.

**Comment by Pythyu** [comment]
Implemented in #59

**Comment by fmauNeko** [comment]
Closed by #59.
