### ISSUE TITLE
Shopping list shows "Cross-DC" or "Cross-World" instead of world name

### ISSUE THREAD

**Issue by SkepticSpoon** [fmauNeko/MarketBoardPlugin#60]
Hi. I don't know if this is intended or a bug, but when I add an item to the shopping list while having the search set to cross-DC or cross-world, the respective option shows in the "World" column of the shopping list instead of the name of the world with the cheapest price.

I have to change the search manually for the respective world in order to have the correct name shown, which obviously isn't possible for worlds of other DC.

This makes it very difficult to know which worlds to go to for each item, and to group purchases together. Otherwise, this is a killer feature, thank you so much!

![image](https://user-images.githubusercontent.com/79415884/188668934-a9a734e1-db8e-48ba-9d4f-1feac6dae391.png)

**Comment by Pythyu** [comment]
Ooh yea definitely a bug, i'm going to fix that ^^
Thx for the feedback

**Comment by Pythyu** [comment]
Fix implemented in #61

**Comment by Pythyu** [comment]
Solved (little cleanup of issues ^^) @fmauNeko
