### ISSUE TITLE
Possible to add launch parameters? 

### ISSUE THREAD

**Issue by itsjop** [fmauNeko/MarketBoardPlugin#7]
I'd love to be able to quick-launch the plugin directly to a search by just typing `/pmb itemname` or something along those lines, and have the board launch directly to the item. As someone who's completely unfamiliar with the xivlauncher options, is this something that would be able to be easily added?

**Comment by aUsefulMethod** [comment]
Is this issue still open?

**Comment by fmauNeko** [comment]
Woops, yes, closed by #8.
Will be released during the weekend.
